---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
data <- read_csv("wildlife_clean.csv") 
```


```{r}
#random adjustment of dates 
date_adjust <- c(-5:5)



data_syth <- data %>%
  mutate(adjust_num = sample(date_adjust, size = nrow(data), replace = TRUE)) %>%
  mutate(adjust_num = ifelse(CALL_SAVED_TIME < as.Date("2018-01-05"), 0, adjust_num)) %>%
 mutate(CALL_SAVED_TIME = CALL_SAVED_TIME + adjust_num) %>%
  select(-adjust_num)

data_syth
```

```{r}
#checking what most common
data %>%
  group_by(CA_ANIMAL_TYPE) %>%
  summarise(count = n(), prop = round(n()/nrow(data)*100, 2)) %>%
  arrange(desc(count))
```

```{r}
#create table to shift around the animal labels 
animal_distinct <- data %>%
  distinct(CA_ANIMAL_TYPE) %>%
mutate(CA_ANIMAL_TYPE_LAG = lag(CA_ANIMAL_TYPE)) 

#manual fix for first lag element
animal_distinct$CA_ANIMAL_TYPE_LAG[1] <- animal_distinct$CA_ANIMAL_TYPE[nrow(animal_distinct)]

animal_distinct
```

```{r}
#change up the regions & animals 
data_syth <- data_syth %>%
  mutate(CALL_REGION = 
case_when(
  CALL_REGION == "Central" ~ "Birmingham", 
  CALL_REGION == "Aberdeen" ~ "Leeds", 
  CALL_REGION == "Edinburgh" ~ "Sheffield", 
  CALL_REGION == "Glasgow" ~ "Manchester", 
  CALL_REGION == "Inverness" ~ "Liverpool",
  TRUE ~ CALL_REGION)) %>%
  left_join(animal_distinct, by = "CA_ANIMAL_TYPE") %>%
  select(-CA_ANIMAL_TYPE) %>%
  rename(CA_ANIMAL_TYPE = CA_ANIMAL_TYPE_LAG)

data_syth
```

```{r}
write_csv(data_syth, "data_syth.csv")
```

